feat/fix: RegularDecisionTree
Dessia-tech/dectree pull request #6
Opened 2023-05-23 21:43 UTC by younesdessia

- feat: add visualize_tree method
- fix: RegularDecisionTree

2023-05-26 15:39 UTC, masfaraud requested changes

2023-05-26 15:39 UTC, masfaraud commented on dectree/dectree.py
> +import graphviz
Not a fan of graphviz import. Is it necessary?

2023-06-01 16:00 UTC, younesdessia commented on dectree/dectree.py
> +import graphviz
@masfaraud 
No, I removed it !

2023-06-09 10:52 UTC, AxelRinghausen requested changes

2023-06-09 10:52 UTC, AxelRinghausen commented on setup.py
> +                        'matplotlib', 'graphviz'])
```suggestion
                        'matplotlib'])
```

2023-08-14 09:13 UTC, younesdessia commented
@AxelRinghausen 
ready for review and merge

2023-09-26 13:32 UTC, masfaraud approved these changes

2023-09-28 16:33 UTC, AxelRinghausen approved these changes

2023-09-28 16:33 UTC, merged